// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEntry } from "./HistoryEntry";

export type ApplyOutcome = { "type": "applied", 
/**
 * The main entry first, then one per matching pin that was updated.
 */
entries: Array<HistoryEntry>, 
/**
 * The box flew to the icon on the desktop (false = celebrated in place).
 */
landed: boolean, 
/**
 * How many matching Start-menu / taskbar-pin shortcuts were left
 * unchanged because Windows won't let Reskin change them (e.g. in
 * the all-users Start menu); absent when there were none.
 */
skippedPins?: number, } | { "type": "needsElevation", ticket: string, reason: string, } | { "type": "unsupported", reason: string, } | { "type": "cancelled" } | { "type": "failed", message: string, hint: string | null, };
