// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyMode } from "./ApplyMode";
import type { ItemId } from "./ItemId";
import type { SizedPng } from "./SizedPng";

export type ApplyRequest = { item: ItemId, 
/**
 * One image per size in `Settings::ico_sizes`.
 */
images: Array<SizedPng>, 
/**
 * Optional design name, stored in history.
 */
designName: string | null, mode: ApplyMode, 
/**
 * Play the collapse → fly → drop animation and commit at landing.
 */
flourish: boolean, 
/**
 * Also update matching Start-menu / taskbar-pin shortcuts.
 */
updatePins: boolean, };
