// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEntry } from "./HistoryEntry";

export type ApplyOutcome = { "type": "applied", entries: Array<HistoryEntry>, 
/**
 * The box flew to the icon on the desktop (false = celebrated in place).
 */
landed: boolean, } | { "type": "needsElevation", ticket: string, reason: string, } | { "type": "unsupported", reason: string, } | { "type": "cancelled" } | { "type": "failed", message: string, hint: string | null, };
