// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxMetrics } from "./BoxMetrics";
import type { Settings } from "./Settings";
import type { WindowKind } from "./WindowKind";

export type BootInfo = { window: WindowKind, version: string, settings: Settings, 
/**
 * Windows has client-area animations turned off.
 */
systemReducedMotion: boolean, 
/**
 * Windows accent colour as `#rrggbb`.
 */
accent: string | null, 
/**
 * e.g. "release 1a2b3c4".
 */
build: string, 
/**
 * Running under `--smoke-test`.
 */
smoke: boolean, 
/**
 * No settings.json existed at startup.
 */
firstRun: boolean, boxMetrics: BoxMetrics, 
/**
 * Windows 11 or later (rounded corners, Mica-era visuals).
 */
windows11: boolean, };
