// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollapseThen } from "./CollapseThen";

/**
 * `box:collapse`: sent to the still hidden box once the editor has
 * collapsed onto its proxy. The box takes on the proxy's final picture
 * (the empty box after `Hide`, `icon` after `Fly` / `Celebrate`) so that it
 * is shown under an identical picture, then confirms with `box_painted`.
 */
export type BoxCollapse = { session: number, then: CollapseThen, 
/**
 * Data URL of the icon the box carries (as in `EditorCmd::Collapse`).
 */
icon: string | null, };
