// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlightPhase } from "./FlightPhase";

export type BoxFlight = { phase: FlightPhase, 
/**
 * Data URL of the icon being carried.
 */
icon: string | null, 
/**
 * How long this leg lasts (ms), so the box can time its squash.
 */
durationMs: number, message: string | null, };
