// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `box:handoff`: sent to the visible box as the editor starts to open over
 * it. The box takes on the picture the editor's proxy draws — the first
 * item's icon with a badge for more than one item, or the empty box — and
 * confirms with `box_painted(session)` once it shows it (an open the box
 * asked for finds it on that picture already).
 */
export type BoxHandoff = { 
/**
 * Box session: numbers every picture handed to the box (`box:handoff`,
 * `box:collapse`), apart from the editor's handoff sessions.
 */
session: number, 
/**
 * Data URL of the first item's icon.
 */
icon: string | null, 
/**
 * Number of items opening.
 */
count: number, };
