// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Box geometry in CSS px. The window is `window` square; the visual box is
 * `visual` square, centred, leaving `margin` on every side for glow/scale.
 */
export type BoxMetrics = { window: number, visual: number, margin: number, radius: number, };
