// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `box:conceal` / `box:reveal`: the box's half of a swap with the
 * editor's proxy, which draws the same picture over it — at every moment
 * exactly one of the two windows paints it. `box:conceal` (open, sent with
 * `EditorCmd::Reveal`) stops painting the box, which is hidden next;
 * `box:reveal` (close, sent with `EditorCmd::Clear`) paints the picture it
 * holds since `box:collapse`. Both pages make their change on their next
 * frame, so the two land in the same composed frame. The box confirms with
 * `box_painted(session)` once its change is on screen.
 */
export type BoxSwap = { 
/**
 * Box session (see `BoxHandoff::session`).
 */
session: number, };
