// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";

/**
 * Where the applied icon sits on screen, for the fly-to-icon flourish.
 */
export type DesktopSpot = { 
/**
 * Screen rect of the icon image in physical px.
 */
rect: Rect, visible: boolean, };
