// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollapseThen } from "./CollapseThen";
import type { EditorView } from "./EditorView";
import type { ItemInfo } from "./ItemInfo";
import type { Rect } from "./Rect";
import type { Settings } from "./Settings";

/**
 * Commands delivered to the editor through `editor_next`.
 */
export type EditorCmd = { "type": "prepare", session: number, boxRect: Rect, items: Array<ItemInfo>, view: EditorView, 
/**
 * Settings snapshot (the editor may have been warm for a while).
 */
settings: Settings, 
/**
 * false = crossfade (reduced motion, user setting or fallback).
 */
morph: boolean, } | { "type": "reveal", session: number, } | { "type": "expand", session: number, } | { "type": "collapse", session: number, boxRect: Rect, then: CollapseThen, 
/**
 * Icon the box should carry (for `Fly`).
 */
icon: string | null, } | { "type": "clear", session: number, } | { "type": "addItems", items: Array<ItemInfo>, } | { "type": "navigate", view: EditorView, } | { "type": "settings", settings: Settings, } | { "type": "heartbeat" };
