// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which view the editor should show when it opens.
 */
export type EditorView = "start" | "edit" | "library" | "history" | "settings" | "systemIcons" | "welcome" | "about";
