// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportKind } from "./ExportKind";
import type { SizedPng } from "./SizedPng";

export type ExportRequest = { kind: ExportKind, 
/**
 * File name without extension.
 */
suggestedName: string, 
/**
 * Ico: every size. Png: exactly one image.
 */
images: Array<SizedPng>, 
/**
 * Project: the .reskin JSON.
 */
data: string | null, };
