// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryState } from "./EntryState";
import type { OriginalIcon } from "./OriginalIcon";
import type { SystemIconId } from "./SystemIconId";
import type { TargetKind } from "./TargetKind";

export type HistoryEntry = { id: string, kind: TargetKind, 
/**
 * Absolute path of the target, or the system icon slug.
 */
target: string, name: string, systemIcon: SystemIconId | null, 
/**
 * The .ico Reskin wrote and pointed the target at.
 */
iconPath: string, original: OriginalIcon, state: EntryState, elevated: boolean, 
/**
 * 48 px PNG thumbnail of the applied icon (base64).
 */
thumb: string | null, designName: string | null, 
/**
 * Unix ms.
 */
appliedAt: number, 
/**
 * Unix ms, set when restored.
 */
restoredAt: number | null, 
/**
 * Entry that this one was applied on top of (same target), if any.
 */
supersedes: string | null, 
/**
 * Set on the extra entries of one apply (matching Start-menu and
 * taskbar-pin shortcuts): the id of the apply's main entry. Undoing
 * the main entry undoes them too.
 */
group?: string, };
