// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One frame of an icon.
 */
export type IconFrame = { width: number, height: number, 
/**
 * base64 PNG, straight alpha.
 */
png: string, };
