// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Access } from "./Access";
import type { ApplyMode } from "./ApplyMode";
import type { IconSource } from "./IconSource";
import type { ItemId } from "./ItemId";
import type { ItemKind } from "./ItemKind";
import type { ItemLocation } from "./ItemLocation";
import type { SystemIconId } from "./SystemIconId";

export type ItemInfo = { id: ItemId, kind: ItemKind, 
/**
 * Display name (file stem / system icon label).
 */
name: string, 
/**
 * Full path, for display only.
 */
path: string, 
/**
 * Shortcut / URL target, for display only.
 */
target: string | null, location: ItemLocation, access: Access, 
/**
 * Apply modes that make sense for this item, preferred first. Empty
 * for items that can only be a design source (images, projects).
 */
modes: Array<ApplyMode>, 
/**
 * Best preview of the current icon as a `data:image/png;base64,` URL
 * (≤256 px, straight alpha), or the image itself for image files.
 */
icon: string | null, iconSource: IconSource, 
/**
 * The item already has a custom icon (set by Reskin or anyone else).
 */
customIcon: boolean, 
/**
 * Reskin's journal has an applied change for this target.
 */
reskinned: boolean, 
/**
 * Shortcut to a Store (AppsFolder) app; IconLocation may be ignored.
 */
storeApp: boolean, systemIcon: SystemIconId | null, 
/**
 * Human-readable notes for the UI (e.g. "Public desktop — needs admin").
 */
notes: Array<string>, };
