// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque handle for an inspected item. Rust keeps the `ItemId -> path`
 * map; mutating commands only ever accept ids, never raw paths.
 */
export type ItemId = string;
