// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryEntry = { id: string, name: string, 
/**
 * base64 PNG thumbnail (≤128 px).
 */
thumb: string, updatedAt: number, bytes: number, };
