// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibrarySave = { 
/**
 * Overwrite this entry; `None` creates a new one.
 */
id: string | null, name: string, thumb: string, 
/**
 * The .reskin JSON.
 */
data: string, };
