// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The icon a target had before Reskin touched it.
 */
export type OriginalIcon = { 
/**
 * Raw icon location (unexpanded), `None` = no custom icon / value absent.
 */
location: string | null, index: number, 
/**
 * For registry-backed system icons: the value existed at all.
 */
existed: boolean, };
