// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An axis-aligned rectangle. The unit (CSS px or physical px) depends on
 * where it is used and is always stated on the field that carries it.
 */
export type Rect = { x: number, y: number, w: number, h: number, };
