// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemId } from "./ItemId";

export type RestoreTarget = { "type": "item", item: ItemId, } | { "type": "entry", id: string, } | { "type": "all" };
