// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Saved box position: top-left of the box *window* in physical pixels plus
 * the monitor it was on, so it can be re-validated when displays change.
 */
export type SavedPos = { x: number, y: number, monitor: string | null, };
