// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfTestCheck } from "./SelfTestCheck";

/**
 * Output of `reskin.exe --self-test`.
 */
export type SelfTest = { version: string, ok: boolean, checks: Array<SelfTestCheck>, };
