// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxSkin } from "./BoxSkin";
import type { MotionPref } from "./MotionPref";
import type { OpenStyle } from "./OpenStyle";
import type { SavedPos } from "./SavedPos";
import type { SizeClass } from "./SizeClass";
import type { ThemeMode } from "./ThemeMode";

export type Settings = { 
/**
 * Schema version of settings.json.
 */
schema: number, theme: ThemeMode, 
/**
 * Tint the UI with the Windows accent colour.
 */
useAccent: boolean, boxSkin: BoxSkin, boxSize: SizeClass, 
/**
 * Opacity of the idle box, 0.25..=1.
 */
idleOpacity: number, boxPosition: SavedPos | null, editorSize: SizeClass, 
/**
 * Animation speed multiplier, 0.5..=2 (2 = twice as fast).
 */
animationSpeed: number, motion: MotionPref, openStyle: OpenStyle, sounds: boolean, autostart: boolean, 
/**
 * Explorer context-menu verb "Reskin this icon" (HKCU).
 */
contextMenu: boolean, 
/**
 * Global hotkey that toggles the box, e.g. "Ctrl+Alt+Shift+R". Empty = off.
 */
hotkey: string, 
/**
 * Opaque windows with DWM rounded corners instead of transparency.
 */
compatibilityMode: boolean, 
/**
 * Destroy the editor when it closes instead of keeping it warm.
 */
lowMemory: boolean, 
/**
 * Hide the box while a fullscreen app / presentation is running.
 */
autoHideFullscreen: boolean, 
/**
 * Also update matching Start-menu and taskbar-pin shortcuts.
 */
updatePins: boolean, 
/**
 * Play the celebratory fly-to-icon animation after applying.
 */
flourish: boolean, 
/**
 * First-run welcome has been shown.
 */
onboarded: boolean, 
/**
 * Most recent colours, newest first, `#rrggbbaa`.
 */
recentColors: Array<string>, 
/**
 * Icon sizes written into .ico files.
 */
icoSizes: Array<number>, 
/**
 * Pixel-art grid used when pixel-art mode starts (16/24/32/48/64).
 */
pixelGrid: number, };
