// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rendered square icon image at one size.
 */
export type SizedPng = { size: number, 
/**
 * base64 PNG (RGBA, straight alpha), `size`×`size`.
 */
png: string, };
