// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Small / medium / large, used for both the box and the editor.
 */
export type SizeClass = "small" | "medium" | "large";
