// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowKind } from "./WindowKind";

export type SmokeReport = { window: WindowKind, 
/**
 * Free-form diagnostics from the page (renderer, timings).
 */
detail: string, };
