// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WallpaperFit } from "./WallpaperFit";

export type WallpaperInfo = { 
/**
 * A wallpaper image is available via `wallpaper()`.
 */
hasImage: boolean, fit: WallpaperFit, 
/**
 * Desktop background colour `#rrggbb`.
 */
background: string, 
/**
 * Monitor size in physical px (the one the box is on).
 */
monitorWidth: number, monitorHeight: number, 
/**
 * Desktop icon size in px (32/48/96…).
 */
iconSize: number, 
/**
 * Windows uses a dark taskbar ("system" theme).
 */
darkTaskbar: boolean, accent: string | null, };
